# Generated by Django 3.0.3 on 2020-12-20 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cust_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdata',
            name='dat_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 20, 18, 40, 34, 334517)),
        ),
    ]
